name: Test Packaing Jar And Upload

on:
  push:
    branches: [ main ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
